/* Copyright (c) 2026 Yao Zeran
 * 
 * The user space layout file. */


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import AuthProvider from "@/features/auth/context/AuthProvider";
import MartFooter from "@/components/MartFooter";
import MartHeader from "@/components/MartHeader";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const UserSpaceLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <MartHeader />
          {children}
          <MartFooter />
        </AuthProvider>
      </body>
    </html>
  );
};


export default UserSpaceLayout;
