/* Copyright (c) 2026, Yao Zeran
 * 
 * The main book mart layout */


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/app/globals.css";

import AuthProvider from "@/features/auth/context/AuthProvider";
import MartHeader from "@/components/MartHeader";
import MartFooter from "@/components/MartFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <MartHeader />
          {children}
          <MartFooter />
        </AuthProvider>
      </body>
    </html>
  );
}


export default RootLayout;
