package com.omniread.backend.service.impl;

import com.omniread.backend.dto.AutoProcurementRequest;
import com.omniread.backend.dto.CreateProcurementRequest;
import com.omniread.backend.dto.LowStockResponse;
import com.omniread.backend.dto.ProcurementResponse;
import com.omniread.backend.dto.UpdateProcurementStatusRequest;
import com.omniread.backend.entity.InventoryRecord;
import com.omniread.backend.entity.ProcurementRequest;
import com.omniread.backend.entity.Product;
import com.omniread.backend.entity.User;
import com.omniread.backend.entity.enums.ProcurementStatus;
import com.omniread.backend.entity.enums.UserRole;
import com.omniread.backend.repository.InventoryRecordRepository;
import com.omniread.backend.repository.ProcurementRequestRepository;
import com.omniread.backend.repository.ProductRepository;
import com.omniread.backend.repository.UserRepository;
import com.omniread.backend.service.ProcurementService;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class ProcurementServiceImpl implements ProcurementService {

    private final ProcurementRequestRepository procurementRequestRepository;
    private final InventoryRecordRepository inventoryRecordRepository;
    private final ProductRepository productRepository;
    private final UserRepository userRepository;

    private static final List<ProcurementStatus> OPEN_STATUSES = Arrays.asList(
        ProcurementStatus.DRAFT,
        ProcurementStatus.AUTO_GENERATED,
        ProcurementStatus.APPROVED,
        ProcurementStatus.SENT,
        ProcurementStatus.ACKNOWLEDGED
    );

    @Override
    @Transactional(readOnly = true)
    public List<ProcurementResponse> listRequests() {
        return procurementRequestRepository.findAll()
            .stream()
            .map(ProcurementResponse::from)
            .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public List<ProcurementResponse> listSupplierRequests(Long supplierId) {
        return procurementRequestRepository.findBySupplierIdOrderByCreatedAtDesc(supplierId)
            .stream()
            .map(ProcurementResponse::from)
            .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public ProcurementResponse createRequest(CreateProcurementRequest request) {
        Product product = productRepository.findById(request.getProductId())
            .orElseThrow(() -> new IllegalArgumentException("Book not found: " + request.getProductId()));
        User supplier = loadSupplier(request.getSupplierId());

        ProcurementRequest procurementRequest = new ProcurementRequest();
        procurementRequest.setRequestNumber(nextRequestNumber());
        procurementRequest.setProduct(product);
        procurementRequest.setSupplier(supplier);
        procurementRequest.setRequestedQuantity(request.getRequestedQuantity());
        procurementRequest.setTriggerReason(request.getTriggerReason());
        procurementRequest.setStatus(ProcurementStatus.DRAFT);
        return ProcurementResponse.from(procurementRequestRepository.save(procurementRequest));
    }

    @Override
    @Transactional
    public List<ProcurementResponse> autoGenerateRequests(AutoProcurementRequest request) {
        User supplier = resolveSupplier(request.getSupplierId());
        return inventoryRecordRepository.findLowStockRecords()
            .stream()
            .filter(record -> !procurementRequestRepository.existsByProductIdAndStatusIn(
                record.getProduct().getId(),
                OPEN_STATUSES
            ))
            .map(record -> createAutoGeneratedRequest(record, supplier))
            .map(ProcurementResponse::from)
            .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public ProcurementResponse updateStatus(
        Long requestId,
        UpdateProcurementStatusRequest request,
        Long actorId,
        boolean supplierActor
    ) {
        ProcurementRequest procurementRequest = procurementRequestRepository.findById(requestId)
            .orElseThrow(() -> new IllegalArgumentException("Procurement request not found: " + requestId));
        if (supplierActor && !procurementRequest.getSupplier().getId().equals(actorId)) {
            throw new IllegalArgumentException("Supplier cannot update another supplier's procurement request");
        }

        ProcurementStatus previousStatus = procurementRequest.getStatus();
        procurementRequest.setStatus(request.getStatus());
        if (request.getExternalRequestId() != null) {
            procurementRequest.setExternalRequestId(request.getExternalRequestId());
        }
        if (request.getStatus() == ProcurementStatus.APPROVED) {
            procurementRequest.setApprovedAt(LocalDateTime.now());
        }
        if (request.getStatus() == ProcurementStatus.FULFILLED && previousStatus != ProcurementStatus.FULFILLED) {
            procurementRequest.setCompletedAt(LocalDateTime.now());
            restockInventory(procurementRequest);
        }
        return ProcurementResponse.from(procurementRequestRepository.save(procurementRequest));
    }

    private ProcurementRequest createAutoGeneratedRequest(InventoryRecord record, User supplier) {
        LowStockResponse lowStock = LowStockResponse.from(record);
        ProcurementRequest procurementRequest = new ProcurementRequest();
        procurementRequest.setRequestNumber(nextRequestNumber());
        procurementRequest.setProduct(record.getProduct());
        procurementRequest.setSupplier(supplier);
        procurementRequest.setRequestedQuantity(lowStock.getSuggestedQuantity());
        procurementRequest.setStatus(ProcurementStatus.AUTO_GENERATED);
        procurementRequest.setTriggerReason("Available stock is at or below reorder threshold");
        return procurementRequestRepository.save(procurementRequest);
    }

    private User resolveSupplier(Long supplierId) {
        if (supplierId != null) {
            return loadSupplier(supplierId);
        }
        return userRepository.findByRole(UserRole.SUPPLIER)
            .stream()
            .findFirst()
            .orElseThrow(() -> new IllegalArgumentException("No supplier account available"));
    }

    private User loadSupplier(Long supplierId) {
        User supplier = userRepository.findById(supplierId)
            .orElseThrow(() -> new IllegalArgumentException("Supplier not found: " + supplierId));
        if (supplier.getRole() != UserRole.SUPPLIER) {
            throw new IllegalArgumentException("Selected user is not a supplier");
        }
        return supplier;
    }

    private void restockInventory(ProcurementRequest procurementRequest) {
        InventoryRecord record = inventoryRecordRepository.findByProductId(procurementRequest.getProduct().getId())
            .orElseThrow(() -> new IllegalArgumentException("Inventory record not found for book: "
                + procurementRequest.getProduct().getId()));
        record.setQuantityOnHand(record.getQuantityOnHand() + procurementRequest.getRequestedQuantity());
        record.setLastRestockedAt(LocalDateTime.now());
        inventoryRecordRepository.save(record);
    }

    private String nextRequestNumber() {
        return "PR-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
    }
}
